### ISSUE TITLE
smbus does not compile; c errors

### ISSUE THREAD

**Issue by thelma1944** [u-fire/Mod-EC#2]
import uFire_Mod_EC
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/uFire_Mod_EC/__init__.py", line 1, in <module>
    from .uFire_Mod_EC import *
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/uFire_Mod_EC/uFire_Mod_EC.py", line 4, in <module>
    import smbus  # pylint: disable=E0401
ModuleNotFoundError: No module named 'smbus'

**Comment by justind000** [comment]
Hello,

smbus is installed by default on most Raspberry Pi OS installations. I guess it isn't on yours. Is it a minimal installation?
Give this a try

`apt-get install python3-smbus`

and see if it works for you.

**Comment by thelma1944** [comment]
Hello

I am running macOS X.  python3-smbus does not work from GitHub.

**Comment by justind000** [comment]
Ah that would be why. The python library is only for use on the Raspberry Pi. To develop on a Mac you will need some Arduino compatible microcontroller and the Arduino library. 

You can find more information here, https://www.ufire.co/ec-isolated-dev-board/.
